FROM node:22.0.0-alpine AS build

WORKDIR /app

COPY package*.json postcss.config.js tailwind.config.js ./

COPY client ./client

RUN npm install && npm run build-css

FROM nginx:alpine

COPY --from=build /app/client/public /usr/share/nginx/html

EXPOSE 80