name: CI

on:
  push:
    branches:
      - main
      - development
      - feature/*
      - ci-cd-setup
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:alpine
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME}}
          POSTGRES_USER: ${{ secrets.DB_USER}}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U cinephoria_user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.0.0"

      - name: Install dependencies
        run: |
          cd server
          npm install
          cd ../client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build
